import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { EXPLORER, ROOT, SEPOLIA_EXPLORER, readDeployment } from './env.js';

/**
 * Writes the real deployment into every place that quotes an address, from one source.
 *
 * The plan this project was built from warned about a specific, observed failure: a stale
 * contract address left behind in one file after a redeploy. The fix is not care, it is
 * not having two copies. `deployments/cc3-testnet.json` is the only hand-free record, and
 * this script is the only thing allowed to copy out of it.
 *
 * Run after `npm run deploy` and again after `npm run e2e`.
 */

type E2e = {
  scenarios: {
    release?: { jobId: string; sourceTx: string; settlementTx: string; paidToBuilder: string };
    challenge?: {
      jobId: string;
      challenger: string;
      sourceTx: string;
      settlementTx: string;
      refundedToBuyer: string;
      bountyToChallenger: string;
    };
    replay?: { settlementTx: string; revertReason: string };
  };
};

const d = readDeployment();
const e2ePath = join(ROOT, 'deployments', 'e2e-results.json');
const e2e: E2e | null = existsSync(e2ePath) ? JSON.parse(readFileSync(e2ePath, 'utf8')) : null;

// ---------------------------------------------------------------- web env
const webEnv = [
  '# Generated by `npm run finalize`. Do not edit by hand.',
  `NEXT_PUBLIC_CREDITCOIN_RPC_URL=https://rpc.cc3-testnet.creditcoin.network`,
  `NEXT_PUBLIC_JOB_ESCROW=${d.jobEscrow}`,
  `NEXT_PUBLIC_WORK_ORACLE=${d.workOracle}`,
  `NEXT_PUBLIC_TEST_USDC=${d.testUsdc}`,
  `NEXT_PUBLIC_DEPLOY_BLOCK=${d.deployBlock ?? 0}`,
  '',
].join('\n');
writeFileSync(join(ROOT, 'web', '.env.production'), webEnv);
writeFileSync(join(ROOT, 'web', '.env.local'), webEnv);
console.log('wrote web/.env.production and web/.env.local');

// ----------------------------------------------------------------- README
const usdc = (v?: string) => (v ? (Number(v) / 1e6).toLocaleString() : '—');

const addresses = [
  '| Contract | Chain | Address |',
  '|---|---|---|',
  `| \`JobEscrow\` | Creditcoin CC3 Testnet | [\`${d.jobEscrow}\`](${EXPLORER}/address/${d.jobEscrow}) |`,
  `| \`SourceRegistry\` | Creditcoin CC3 Testnet | [\`${d.sourceRegistry}\`](${EXPLORER}/address/${d.sourceRegistry}) |`,
  `| \`TestUSDC\` | Creditcoin CC3 Testnet | [\`${d.testUsdc}\`](${EXPLORER}/address/${d.testUsdc}) |`,
  `| \`WorkOracle\` | Ethereum Sepolia | [\`${d.workOracle}\`](${SEPOLIA_EXPLORER}/address/${d.workOracle}) |`,
].join('\n');

const s = e2e?.scenarios;
const transactions = s
  ? [
      '| # | What it proves | Source transaction (Sepolia) | Settlement (Creditcoin) |',
      '|---|---|---|---|',
      s.release
        ? `| 1 | A proved \`WorkCompleted\` pays the builder ${usdc(s.release.paidToBuilder)} tUSDC | [\`${s.release.sourceTx.slice(0, 14)}…\`](${SEPOLIA_EXPLORER}/tx/${s.release.sourceTx}) | [\`${s.release.settlementTx.slice(0, 14)}…\`](${EXPLORER}/tx/${s.release.settlementTx}) |`
        : '',
      s.challenge
        ? `| 2 | A proved \`WorkFailed\`, submitted by [\`${s.challenge.challenger.slice(0, 10)}…\`](${EXPLORER}/address/${s.challenge.challenger}) — **neither the buyer nor the builder** — refunds ${usdc(s.challenge.refundedToBuyer)} tUSDC and pays that wallet a ${usdc(s.challenge.bountyToChallenger)} tUSDC bounty | [\`${s.challenge.sourceTx.slice(0, 14)}…\`](${SEPOLIA_EXPLORER}/tx/${s.challenge.sourceTx}) | [\`${s.challenge.settlementTx.slice(0, 14)}…\`](${EXPLORER}/tx/${s.challenge.settlementTx}) |`
        : '',
      s.replay
        ? `| 3 | Replaying proof #1 is refused on-chain (\`${s.replay.revertReason.slice(0, 60)}\`) | — | [\`${s.replay.settlementTx.slice(0, 14)}…\`](${EXPLORER}/tx/${s.replay.settlementTx}) |`
        : '',
    ]
      .filter(Boolean)
      .join('\n')
  : '_Not run yet._';

const block = [
  '<!-- BEGIN:DEPLOYMENT -->',
  '## Deployed',
  '',
  addresses,
  '',
  '### The three transactions',
  '',
  transactions,
  '',
  `_Deployed ${d.deployedAt} by \`${d.deployer}\` · CC3 chain id ${d.network.creditcoinChainId} · source chain key ${d.network.sourceChainKey}._`,
  '<!-- END:DEPLOYMENT -->',
].join('\n');

const readmePath = join(ROOT, 'README.md');
let readme = readFileSync(readmePath, 'utf8');
if (readme.includes('<!-- BEGIN:DEPLOYMENT -->')) {
  readme = readme.replace(/<!-- BEGIN:DEPLOYMENT -->[\s\S]*?<!-- END:DEPLOYMENT -->/, block);
} else {
  // Insert immediately after the opening tagline so evidence sits above the prose.
  readme = readme.replace(/\n---\n/, `\n---\n\n${block}\n\n---\n`);
}
writeFileSync(readmePath, readme);
console.log('README.md deployment block updated');
console.log('\n' + block);
