import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { EXPLORER, ROOT, SEPOLIA_EXPLORER, readDeployment } from './env.js';

/**
 * Writes the real deployment into every place that quotes an address, from one source.
 *
 * The plan this project was built from warned about a specific, observed failure: a stale
 * contract address left behind in one file after a redeploy. The fix is not care, it is
 * not having two copies. `deployments/cc3-testnet.json` is the only hand-kept record, and
 * this script is the only thing allowed to copy out of it.
 *
 * Run after `npm run deploy` and again after `npm run e2e`.
 */

type E2e = {
  scenarios: {
    release?: { jobId: string; sourceTx: string; settlementTx: string; paidToBuilder: string };
    challenge?: {
      jobId: string;
      challenger: string;
      sourceTx: string;
      settlementTx: string;
      refundedToBuyer: string;
      bountyToChallenger: string;
    };
    replay?: { settlementTx: string; revertReason: string };
    delivery?: {
      token: string;
      beneficiary: string;
      minDelivery: string;
      sourceTx: string;
      settlementTx: string;
      paidToBuilder: string;
      submittedBy: string;
    };
    selfCertify?: {
      attemptedBy: string;
      sourceTx: string;
      status: number;
      revertReason: string;
      builderIsReporter: boolean;
    };
  };
};

const d = readDeployment();
const e2ePath = join(ROOT, 'deployments', 'e2e-results.json');
const e2e: E2e | null = existsSync(e2ePath) ? JSON.parse(readFileSync(e2ePath, 'utf8')) : null;
const s = e2e?.scenarios;

// ---------------------------------------------------------------- web config
const webEnv = [
  '# Generated by `npm run finalize`. Do not edit by hand.',
  'NEXT_PUBLIC_CREDITCOIN_RPC_URL=https://rpc.cc3-testnet.creditcoin.network',
  `NEXT_PUBLIC_JOB_ESCROW=${d.jobEscrow}`,
  `NEXT_PUBLIC_WORK_ORACLE=${d.workOracle}`,
  `NEXT_PUBLIC_TEST_USDC=${d.testUsdc}`,
  `NEXT_PUBLIC_DEPLOY_BLOCK=${d.deployBlock ?? 0}`,
  '',
].join('\n');
writeFileSync(join(ROOT, 'web', '.env.production'), webEnv);
writeFileSync(join(ROOT, 'web', '.env.local'), webEnv);
console.log('wrote web/.env.production and web/.env.local');

// A committed copy as well. These are public facts, not secrets, and Vercel does not upload
// gitignored .env files: a build there would otherwise come up with nothing configured and
// silently render an empty page. Every link and hash the site shows comes from this file,
// so the site cannot drift from the deployment the way a hand-typed URL can.
const webDeployment = {
  jobEscrow: d.jobEscrow,
  workOracle: d.workOracle,
  testUsdc: d.testUsdc,
  sourceRegistry: d.sourceRegistry,
  deployBlock: d.deployBlock ?? 0,
  creditcoinChainId: d.network.creditcoinChainId,
  repoUrl: d.repoUrl ?? '',
  transactions: {
    release: s?.release
      ? {
          settlementTx: s.release.settlementTx,
          sourceTx: s.release.sourceTx,
          paidToBuilder: s.release.paidToBuilder,
        }
      : null,
    challenge: s?.challenge
      ? {
          settlementTx: s.challenge.settlementTx,
          sourceTx: s.challenge.sourceTx,
          challenger: s.challenge.challenger,
          refundedToBuyer: s.challenge.refundedToBuyer,
          bountyToChallenger: s.challenge.bountyToChallenger,
        }
      : null,
    replay: s?.replay
      ? { settlementTx: s.replay.settlementTx, revertReason: s.replay.revertReason }
      : null,
    delivery: s?.delivery
      ? {
          token: s.delivery.token,
          beneficiary: s.delivery.beneficiary,
          minDelivery: s.delivery.minDelivery,
          sourceTx: s.delivery.sourceTx,
          settlementTx: s.delivery.settlementTx,
          paidToBuilder: s.delivery.paidToBuilder,
          submittedBy: s.delivery.submittedBy,
        }
      : null,
    selfCertify: s?.selfCertify
      ? {
          sourceTx: s.selfCertify.sourceTx,
          attemptedBy: s.selfCertify.attemptedBy,
          status: s.selfCertify.status,
          revertReason: s.selfCertify.revertReason,
          builderIsReporter: s.selfCertify.builderIsReporter,
        }
      : null,
  },
};
writeFileSync(
  join(ROOT, 'web', 'lib', 'deployment.json'),
  JSON.stringify(webDeployment, null, 2) + '\n',
);
console.log('wrote web/lib/deployment.json');

// ----------------------------------------------------------------- README
const usdc = (v?: string) => (v ? (Number(v) / 1e6).toLocaleString() : '?');
const cut = (h: string) => `${h.slice(0, 14)}...`;

const live = [
  d.webUrl ? `**Live console:** ${d.webUrl}` : '',
  d.repoUrl ? `**Repository:** ${d.repoUrl}` : '',
]
  .filter(Boolean)
  .join('  \n');

const addresses = [
  '| Contract | Chain | Address |',
  '|---|---|---|',
  `| \`JobEscrow\` | Creditcoin CC3 Testnet | [\`${d.jobEscrow}\`](${EXPLORER}/address/${d.jobEscrow}) |`,
  `| \`SourceRegistry\` | Creditcoin CC3 Testnet | [\`${d.sourceRegistry}\`](${EXPLORER}/address/${d.sourceRegistry}) |`,
  `| \`TestUSDC\` | Creditcoin CC3 Testnet | [\`${d.testUsdc}\`](${EXPLORER}/address/${d.testUsdc}) |`,
  `| \`WorkOracle\` | Ethereum Sepolia | [\`${d.workOracle}\`](${SEPOLIA_EXPLORER}/address/${d.workOracle}) |`,
].join('\n');

const rows: string[] = [];
if (s?.release) {
  rows.push(
    `| 1 | A proved \`WorkCompleted\` pays the builder ${usdc(s.release.paidToBuilder)} tUSDC | [\`${cut(s.release.sourceTx)}\`](${SEPOLIA_EXPLORER}/tx/${s.release.sourceTx}) | [\`${cut(s.release.settlementTx)}\`](${EXPLORER}/tx/${s.release.settlementTx}) |`,
  );
}
if (s?.challenge) {
  rows.push(
    `| 2 | A proved \`WorkFailed\`, submitted by [\`${s.challenge.challenger.slice(0, 10)}...\`](${EXPLORER}/address/${s.challenge.challenger}), **neither the buyer nor the builder**, refunds ${usdc(s.challenge.refundedToBuyer)} tUSDC and pays that wallet a ${usdc(s.challenge.bountyToChallenger)} tUSDC bounty | [\`${cut(s.challenge.sourceTx)}\`](${SEPOLIA_EXPLORER}/tx/${s.challenge.sourceTx}) | [\`${cut(s.challenge.settlementTx)}\`](${EXPLORER}/tx/${s.challenge.settlementTx}) |`,
  );
}
if (s?.replay) {
  rows.push(
    `| 3 | Replaying proof #1 is refused on-chain (\`${s.replay.revertReason.slice(0, 60)}\`) | | [\`${cut(s.replay.settlementTx)}\`](${EXPLORER}/tx/${s.replay.settlementTx}) |`,
  );
}

if (s?.delivery) {
  const eth = (v: string) => (Number(v) / 1e18).toString();
  rows.push(
    `| ${rows.length + 1} | Settled with **no oracle and no reporter at all**. The acceptance criterion was an on-chain delivery: the builder moved at least ${eth(s.delivery.minDelivery)} WETH to the buyer, and [\`${s.delivery.token.slice(0, 10)}...\`](${SEPOLIA_EXPLORER}/address/${s.delivery.token}), a token that has never heard of this project, said so. Paid the builder ${usdc(s.delivery.paidToBuilder)} tUSDC | [\`${cut(s.delivery.sourceTx)}\`](${SEPOLIA_EXPLORER}/tx/${s.delivery.sourceTx}) | [\`${cut(s.delivery.settlementTx)}\`](${EXPLORER}/tx/${s.delivery.settlementTx}) |`,
  );
}

if (s?.selfCertify) {
  rows.push(
    `| ${rows.length + 1} | The builder calls \`reportCompleted\` for their own job on the source chain and is refused there, before any proof can exist. \`isReporter(builder)\` is \`${s.selfCertify.builderIsReporter}\` | [\`${cut(s.selfCertify.sourceTx)}\`](${SEPOLIA_EXPLORER}/tx/${s.selfCertify.sourceTx}) reverted | |`,
  );
}

const transactions = rows.length
  ? [
      '| # | What it proves | Source transaction (Sepolia) | Settlement (Creditcoin) |',
      '|---|---|---|---|',
      ...rows,
    ].join('\n')
  : '_Not run yet._';

const block = [
  '<!-- BEGIN:DEPLOYMENT -->',
  '## Deployed',
  '',
  live,
  '',
  addresses,
  '',
  rows.length === 1 ? '### The transaction' : `### The ${rows.length} transactions`,
  '',
  transactions,
  '',
  `_Deployed ${d.deployedAt} by \`${d.deployer}\` on CC3 chain id ${d.network.creditcoinChainId}, source chain key ${d.network.sourceChainKey}, escrow from block ${d.deployBlock ?? 0}._`,
  '<!-- END:DEPLOYMENT -->',
].join('\n');


// ------------------------------------------------------------------ FACTS
// One generated sheet of every figure the deck and the video are allowed to quote.
// A hackathon deck's classic failure is a number nobody re-checked after a redeploy, so
// the numbers are not retyped anywhere: they are produced here from the deployment record
// and the demo run, and docs/deck-prompt.md points at this file instead of copying them.
const na = '_not run yet_';
const facts = [
  '# Facts',
  '',
  '**Generated by `npm run finalize`. Do not edit by hand.**',
  '',
  'Every figure the deck and the demo video are allowed to quote. If a number is not here,',
  'it has not been produced by a real run, and it does not go on a slide.',
  '',
  '## Links',
  '',
  '| | |',
  '|---|---|',
  `| Live console | ${d.webUrl ?? na} |`,
  `| Verify a proof | ${d.webUrl ? d.webUrl + '/verify' : na} |`,
  `| Repository | ${d.repoUrl ?? na} |`,
  `| Explorer | ${EXPLORER} |`,
  '',
  '## Contracts',
  '',
  '| Contract | Chain | Address |',
  '|---|---|---|',
  `| \`JobEscrow\` | Creditcoin CC3 Testnet | \`${d.jobEscrow}\` |`,
  `| \`SourceRegistry\` | Creditcoin CC3 Testnet | \`${d.sourceRegistry}\` |`,
  `| \`TestUSDC\` | Creditcoin CC3 Testnet | \`${d.testUsdc}\` |`,
  `| \`WorkOracle\` | Ethereum Sepolia | \`${d.workOracle}\` |`,
  '| Block Prover precompile | Creditcoin CC3 Testnet | `0x0000000000000000000000000000000000000FD2` |',
  '',
  `Creditcoin CC3 Testnet chain id **${d.network.creditcoinChainId}**. Source chain Ethereum Sepolia,`,
  `Attestcoin chain key **${d.network.sourceChainKey}**, EVM chain id **${d.network.sourceEvmChainId}**.`,
  `Escrow deployed at block **${d.deployBlock ?? 0}** on ${d.deployedAt}.`,
  '',
  '## The demo run',
  '',
  transactions,
  '',
  '## Job economics in the demo',
  '',
  '| | |',
  '|---|---|',
  `| Payout | ${s?.release ? usdc(String(BigInt(s.release.paidToBuilder) - BigInt(s.challenge?.bountyToChallenger ?? '0') * 2n)) : na} tUSDC nominal, 1,000 |`,
  '| Builder bond | 20 percent of the payout |',
  '| Challenger bounty | 50 percent of the bond |',
  `| Paid to builder on release | ${s?.release ? usdc(s.release.paidToBuilder) : na} tUSDC |`,
  `| Refunded to buyer on challenge | ${s?.challenge ? usdc(s.challenge.refundedToBuyer) : na} tUSDC |`,
  `| Bounty to the challenger | ${s?.challenge ? usdc(s.challenge.bountyToChallenger) : na} tUSDC |`,
  `| Challenger address | ${s?.challenge ? '\`' + s.challenge.challenger + '\`' : na} |`,
  '',
  '## Rules that must hold on any slide',
  '',
  '1. No project entered in this hackathon is named, described or compared against.',
  '2. Every number on a slide appears in this file.',
  '3. The limitations slide gets the same care as the evidence slide.',
  '4. Transaction hashes are shown complete, never truncated, so they can be pasted.',
  '',
].join('\n');
writeFileSync(join(ROOT, 'docs', 'FACTS.md'), facts + '\n');
console.log('wrote docs/FACTS.md');

const readmePath = join(ROOT, 'README.md');
let readme = readFileSync(readmePath, 'utf8');
if (readme.includes('<!-- BEGIN:DEPLOYMENT -->')) {
  readme = readme.replace(/<!-- BEGIN:DEPLOYMENT -->[\s\S]*?<!-- END:DEPLOYMENT -->/, block);
} else {
  readme = readme.replace(/\n---\n/, `\n---\n\n${block}\n\n---\n`);
}
writeFileSync(readmePath, readme);
console.log('README.md deployment block updated');
